Resources:
  RoleSaya:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
            - sagemaker.amazonaws.com
            - codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
      RoleName: AturanSayaUntukSageMaker
  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
        DomainName: DomainTutorial
        AuthMode: IAM
        DefaultUserSettings: 
           ExecutionRole: !GetAtt RoleSaya.Arn
        VpcId: vpc-8fb875e9
        SubnetIds:
          - subnet-2c5cea4a
          - subnet-ef5439b6
          - subnet-509e3818
  HerleySageMakerUser:
    Type: AWS::SageMaker::UserProfile
    Properties: 
      DomainId: !GetAtt SageMakerDomain.DomainId
      UserProfileName: herley